---
- name: Remove Apache server
  hosts: node1
  become: true
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Stopping Services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: true
      loop:
        - httpd
        - dhcpd
    - name: Remove dependencies (packages)
      ansible.builtin.package:
        name:
          - httpd
          - dhcpd
        state: absent
    - name: Remove files
      ansible.builtin.file:
        path: |
          /root/index.html
          /var/www/html/index.html
          /etc/httpd/conf/httpd.conf
          /etc/httpd/conf/prov_callback.conf
          /etc/dhcp/hosts.csv
          /etc/dhcp/dhcpd.conf
        state: absent
