---
- name: Apache server installed
  hosts: node1
  become: yes
  tasks:
  - name: latest Apache version installed
    ansible.builtin.package:
      name: httpd
      state: latest
  - name: Apache enabled and running
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started
  # - name: copy web.html
  #   ansible.builtin.copy:
  #     src: files/index.html
  #     dest: /var/www/html/index.html
  - name: Index Page
    ansible.builtin.copy:
      dest: /var/www/html/index.html
      content: |
        Bem vindo ao teste Ansible
