---
# defaults file for roles/network_services
network_services_csv_src_path: files/hosts.csv
network_services_csv_dst_path: /etc/dhcp/hosts.csv

network_services_templ_src: dhcpd.conf.j2
network_services_templ_dst: /etc/dhcp/dhcpd.conf

dhcp_subnet: 192.168.15.0
dhcp_subnet_mask: 255.255.255.0
dhcp_range_start: 192.168.15.222
dhcp_range_end: 192.168.15.230
dhcp_router: 192.168.15.1
